//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursive.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cursive.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created sucessfully.
        /// </summary>
        internal static string CREATED_SUCESSFULLY {
            get {
                return ResourceManager.GetString("CREATED_SUCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} already exists.
        /// </summary>
        internal static string EXISTS {
            get {
                return ResourceManager.GetString("EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email or password is invalid..
        /// </summary>
        internal static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token.
        /// </summary>
        internal static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login sucessfully.
        /// </summary>
        internal static string LOGIN_SUCESSFULLY {
            get {
                return ResourceManager.GetString("LOGIN_SUCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found document = {}.
        /// </summary>
        internal static string NOT_FOUND_DOCUMENT {
            get {
                return ResourceManager.GetString("NOT_FOUND_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found documents.
        /// </summary>
        internal static string NOT_FOUND_DOCUMENTS {
            get {
                return ResourceManager.GetString("NOT_FOUND_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found expire time in configuration..
        /// </summary>
        internal static string NOT_FOUND_EXPIRE_TIME {
            get {
                return ResourceManager.GetString("NOT_FOUND_EXPIRE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found secret key in configuration..
        /// </summary>
        internal static string NOT_FOUND_SECRET_KEY {
            get {
                return ResourceManager.GetString("NOT_FOUND_SECRET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found user  = {0}.
        /// </summary>
        internal static string NOT_FOUND_USER {
            get {
                return ResourceManager.GetString("NOT_FOUND_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found user with id {0}.
        /// </summary>
        internal static string NOT_FOUND_USER_ID {
            get {
                return ResourceManager.GetString("NOT_FOUND_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string SUCCESSFUL {
            get {
                return ResourceManager.GetString("SUCCESSFUL", resourceCulture);
            }
        }
    }
}
